--建立临时表空间
CREATE TEMPORARY TABLESPACE BBTYTMP
TEMPFILE 'F:\app\wsd\oradata\orcl\BBTYTMP.DBF' 
SIZE 32M 
AUTOEXTEND ON 
NEXT 32M MAXSIZE 2048M
EXTENT MANAGEMENT LOCAL;

--建立表空间
CREATE TABLESPACE BBTY
LOGGING
DATAFILE 'F:\app\wsd\oradata\orcl\BBTY.DBF' 
SIZE 32M 
AUTOEXTEND ON 
NEXT 32M MAXSIZE 2048M
EXTENT MANAGEMENT LOCAL;

--建立索引空间
CREATE TABLESPACE BBTYIDX
LOGGING
DATAFILE 'F:\app\wsd\oradata\orcl\BBTYIDX.DBF' 
SIZE 32M 
AUTOEXTEND ON 
NEXT 32M MAXSIZE 2048M
EXTENT MANAGEMENT LOCAL;

--创建用户并指定表空间
CREATE USER bbty IDENTIFIED BY bbty
DEFAULT TABLESPACE BBTYIDX
TEMPORARY TABLESPACE BBTYTMP;

GRANT CONNECT,RESOURCE TO bbty;
GRANT 
　　CREATE SESSION, CREATE ANY TABLE, CREATE ANY VIEW ,CREATE ANY INDEX, CREATE ANY PROCEDURE,
　　ALTER ANY TABLE, ALTER ANY PROCEDURE,
　　DROP ANY TABLE, DROP ANY VIEW, DROP ANY INDEX, DROP ANY PROCEDURE,
　　SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE
　　TO bbty;

